version: '3.8'

services:
  frontend:
    image: sarthakjazz/todo-app-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - todo-network
    depends_on:
      - backend
      - websocket
    restart: unless-stopped

  backend:
    image: sarthakjazz/todo-app-backend:latest
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - todo-network
    restart: unless-stopped

  websocket:
    image: sarthakjazz/todo-app-websocket:latest
    container_name: websocket
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - todo-network
    restart: unless-stopped

networks:
  todo-network:
    driver: bridge
    name: todo-network
