name: Deploy the frontend
on: 
  push:
      branch: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          tags: |
            sarthakjazz/todo-app-frontend:${{ github.sha }}
            sarthakjazz/todo-app-frontend:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}

      # - name: Deploy to VM
      #   run: |
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
      #     chmod 600 ~/ssh_key

      #     ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker stop frontend || true"

      #     ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker rm frontend || true"

      #     ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker pull sarthakjazz/todo-app-frontend:${{ github.sha }}"

      #     ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker run -d -e DATABASE_URL='${{ secrets.DATABASE_URL }}' --name frontend -p 3000:3000 sarthakjazz/todo-app-frontend:${{ github.sha }}"

      #     ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@${{ secrets.WS_AWS_SERVER_IP }} "docker image prune -f"